services:
    SendGrid.SendGridService:
        class: SendGrid
        arguments:
            username: "%savch_sendgrid.api_user%"
            password: "%savch_sendgrid.api_key%"

    SendGrid.SendGridMailerService:
        class:      Savch\SendgridBundle\Service\SendGridTemplatingMailerService
        arguments:
            sendGrid:               "@SendGrid.SendGridService"
            templating:             "@templating"
            throwExceptionsOnFail:  true
            credentials:
                username: "%savch_sendgrid.api_user%"
                password: "%savch_sendgrid.api_key%"
