services:
    sendgrid.sendgridservice:
        class: SendGrid
        arguments:
            - "%savch_sendgrid.api_key%"

    sendgrid.sendgridmailerservice:
        class:      Savch\SendgridBundle\Service\SendGridTemplatingMailerService
        arguments:
            - "@sendgrid.sendgridservice"
            - "@templating"
            - true
